version: '3.8'
services:
  mysql:
    image: mysql
    container_name: mysql
    volumes:
      - data:/var/lib/mysql
    env_file:
      - "./.env"
  api:
    build: 
      context: .
      dockerfile: api.dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./.env
volumes:
  data:
